# Generated by Django 4.0.6 on 2022-07-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_car_gas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='gas',
            new_name='gases',
        ),
    ]
