# Generated by Django 4.0.6 on 2022-07-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cat',
            new_name='car',
        ),
    ]
